// <auto-generated />
namespace SchoolProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Course_and_Assignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_and_Assignment));
        
        string IMigrationMetadata.Id
        {
            get { return "202005151150436_Course_and_Assignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
